
LEVELS = [
    {
            'columns' : 9,
            'rows' : 9,
            'bombs' : 10,
            'flags' : 12,
            'time' : 160,
            'description' : 'Easy as pie',
            'autoblink' : 5,
    },
    {
            'columns' : 9,
            'rows' : 9,
            'bombs' : 10,
            'flags' : 12,
            'time' : 80,
            'description' : 'Can you do it faster?',
            'autoblink' : 5,
    },
    {
            'columns' : 9,
            'rows' : 9,
            'bombs' : 10,
            'flags' : 15,
            'time' : 60,
            'description' : 'Use flags to cover bombs',
            'autoblink' : 5,
    },
    {
            'columns' : 9,
            'rows' : 9,
            'bombs' : 10,
            'flags' : 15,
            'time' : 35,
            'description' : 'Speed round!',
            'autoblink' : 5,
    },
    {
            'columns' : 16,
            'rows' : 16,
            'bombs' : 20,
            'flags' : 25,
            'time' : 80,
            'description' : "Let's increase the board size",
            'autoblink' : 5,
    },
    {
            'columns' : 16,
            'rows' : 16,
            'bombs' : 40,
            'flags' : 40,
            'time' : 300,
            'description' : '',
            'autoblink' : 5,
    },
    {
            'columns' : 30,
            'rows' : 16,
            'bombs' : 99,
            'flags' : 99,
            'time' : 500,
            'description' : 'Just like the original',
            'autoblink' : 5,
    },
]
